bug-fix grpc

diff --git a/dev/ibc/two-chainz b/dev/ibc/two-chainz
--- a/dev/ibc/two-chainz
+++ b/dev/ibc/two-chainz
@@ -82,61 +82,64 @@ mkdir -p $GAIA_DATA && cd $GAIA_DATA && cd ../
 #
 #rly config add-paths configs/demo/paths
 
-#
-pwd=${PWD}
-echo  "relayer"
-relayer_path=${GOPATH}/src/github.com/cosmos/relayer
-if [ ! -d ${relayer_path} ];then
-  mkdir -p ${GOPATH}/src/github.com/cosmos/
-  cd ${GOPATH}/src/github.com/cosmos/
-  git clone https://github.com/cosmos/relayer.git
-fi
-
-cd ${GOPATH}/src/github.com/cosmos/relayer
-git checkout v1.0.0
-if [ $? -ne 0 ]; then
-    echo "checkout failed ,use stash or commit first"
-    exit
-fi
-
-rm -rf vendor
-rm -rf ~/.relayer
-echo "Building Relayer..."
-make install
-cd ${pwd}
-echo "Generating rly configurations..."
-rly config init
-rly config add-chains configs/demo/chains
-
-#SEED0=$(jq -r '.name' $GAIA_DATA/exchain-100/key_seed.json)
-#SEED1=$(jq -r '.name' $GAIA_DATA/exchain-101/key_seed.json)
-#echo ${SEED0}
-#echo ${SEED1}
-
-#mem=""
-#function  getMem() {
-#    chainName=${1}
-#    rm -f ./temp.json
-#    rly keys add ${chainName} admin16 >  ./temp.json
-#    mem=$(jq -r '.mnemonic' ./temp.json)
-#}
-#
-##echo "Key $(rly keys restore exchain-100 testkey "$SEED0") imported from exchain-100 to relayer..."
-##echo "Key $(rly keys restore exchain-101 testkey "$SEED1") imported from exchain-101 to relayer..."
-#getMem exchain-100
-#echo "Key $(rly keys restore exchain-100 testkey "$mem") imported from exchain-100 to relayer..."
-#getMem exchain-101
-#echo "Key $(rly keys restore exchain-101 testkey "$mem") imported from exchain-101 to relayer..."
 
 
-echo "Key $(rly keys add exchain-100 admin16 ) imported from exchain-100 to relayer..."
-echo "Key $(rly keys add exchain-101 admin16 ) imported from exchain-101 to relayer..."
 
 #
-echo "current chains:"
-rly chains list
+#pwd=${PWD}
+#echo  "relayer"
+##relayer_path=${GOPATH}/src/github.com/cosmos/relayer
+##if [ ! -d ${relayer_path} ];then
+##  mkdir -p ${GOPATH}/src/github.com/cosmos/
+##  cd ${GOPATH}/src/github.com/cosmos/
+##  git clone https://github.com/cosmos/relayer.git
+##fi
+##
+#cd ${GOPATH}/src/github.com/cosmos/relayer
+##git checkout v1.0.0
+#if [ $? -ne 0 ]; then
+#    echo "checkout failed ,use stash or commit first"
+#    exit
+#fi
 #
+##rm -rf vendor
+##rm -rf ~/.relayer
+##echo "Building Relayer..."
+##make install
+##cd ${pwd}
+#echo "Generating rly configurations..."
+#rly config init
+#rly config add-chains configs/demo/chains
 #
-rly config add-paths configs/demo/paths
-echo "current pathes"
-rly paths list
+##SEED0=$(jq -r '.name' $GAIA_DATA/exchain-100/key_seed.json)
+##SEED1=$(jq -r '.name' $GAIA_DATA/exchain-101/key_seed.json)
+##echo ${SEED0}
+##echo ${SEED1}
+#
+##mem=""
+##function  getMem() {
+##    chainName=${1}
+##    rm -f ./temp.json
+##    rly keys add ${chainName} admin16 >  ./temp.json
+##    mem=$(jq -r '.mnemonic' ./temp.json)
+##}
+##
+###echo "Key $(rly keys restore exchain-100 testkey "$SEED0") imported from exchain-100 to relayer..."
+###echo "Key $(rly keys restore exchain-101 testkey "$SEED1") imported from exchain-101 to relayer..."
+##getMem exchain-100
+##echo "Key $(rly keys restore exchain-100 testkey "$mem") imported from exchain-100 to relayer..."
+##getMem exchain-101
+##echo "Key $(rly keys restore exchain-101 testkey "$mem") imported from exchain-101 to relayer..."
+#
+##
+#echo "Key $(rly keys add exchain-100 admin16 ) imported from exchain-100 to relayer..."
+#echo "Key $(rly keys add exchain-101 admin16 ) imported from exchain-101 to relayer..."
+##
+###
+#echo "current chains:"
+#rly chains list
+###
+###
+#rly config add-paths configs/demo/paths
+#echo "current pathes"
+##rly paths list
